### ISSUE TITLE
ReuseEngineTest failure

### ISSUE THREAD

**Issue by keturn** [Terasology/ModuleTestingEnvironment#45]
[CI says](http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/view/Unhealthy/job/M/job/ModuleTestingEnvironment/job/develop/lastCompletedBuild/testReport/org.terasology.moduletestingenvironment/ReuseEngineTest/initializationError/):

```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.terasology.engine.rendering.nui.internal.TerasologyCanvasImpl.<init>(TerasologyCanvasImpl.java:45)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.<init>(NUIManagerInternal.java:116)
	at org.terasology.engine.core.modes.StateMainMenu.init(StateMainMenu.java:82)
```

in ReuseEngineTest.

That TerasologyCanvasImpl is: https://github.com/MovingBlocks/Terasology/blob/3b8c37df89fc0839cc84bda1e325310e1f12ed86/engine/src/main/java/org/terasology/rendering/nui/internal/TerasologyCanvasImpl.java#L43-L45

[and I'm not sure when GitHub will and won't inline the source listing. Is it only when the issue is in the same repository as the source? or the same organization?]

so `Assets.getTexture("engine:white")` ... the engine module isn't loaded, or some asset file is not in the right place?

**Comment by keturn** [comment]
I think this was fixed by https://github.com/MovingBlocks/Terasology/pull/4581

[tests passed](http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/view/Iota/job/M/job/ModuleTestingEnvironment/job/develop/35/testReport/)
